name: Build V8

on:
  push:
    branches: [master]
    paths:
      - "V8_VERSION"
      - "CHROMIUM_VERSION"
      - "builders/**"
      - ".github/workflows/build.yml"

jobs:
  version_reader:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.got_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: got_version
        run: |
          cd $GITHUB_WORKSPACE
          echo "::set-output name=version::$(<./V8_VERSION)"

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos
            platform_name: macOS
            os: macos-latest
            arch: arm64
            arch_name: ARM64
            scheme: release
            scheme_name: Release
          - platform: macos
            platform_name: macOS
            os: macos-latest
            arch: arm64
            arch_name: ARM64
            scheme: debug
            scheme_name: Debug
          - platform: linux
            platform_name: Linux
            os: ubuntu-latest
            arch: arm64
            arch_name: ARM64
            scheme: release
            scheme_name: Release
          - platform: linux
            platform_name: Linux
            os: ubuntu-latest
            arch: x64
            arch_name: x86-64
            scheme: release
            scheme_name: Release
    name:
      Build ${{ matrix.scheme_name }} ${{ matrix.platform_name }} ${{
      matrix.arch_name }}
    runs-on: ${{ matrix.os }}
    needs: [version_reader, create_release]
    outputs:
      artifact: ${{ steps.artifact.outputs.artifact }}
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: |
          cd $GITHUB_WORKSPACE
          bash ./builders/v8.sh
        env:
          VERSION: ${{ needs.version_reader.outputs.version }}
          SCHEME: ${{ matrix.scheme }}
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
      - name: Upload Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ~/v8/v8.zip
          asset_name:
            v8-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.scheme
            }}-${{ needs.version_reader.outputs.version }}.zip
          asset_content_type: application/zip

  headers:
    name: Headers and Documentation
    runs-on: ubuntu-18.04
    needs: [create_release, version_reader]
    steps:
      - uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          cd $GITHUB_WORKSPACE
          sh ./builders/v8-docs.sh ${{ needs.version_reader.outputs.version }}
      - name: Build Archives
        run: |
          zip -r ~/v8/docs.zip ~/docs
          zip -r ~/v8/headers.zip ~/v8/v8/include
      - name: Upload Documentation
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ~/v8/docs.zip
          asset_name: v8-docs-${{ needs.version_reader.outputs.version }}.zip
          asset_content_type: application/zip
      - name: Upload Headers
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ~/v8/headers.zip
          asset_name: v8-headers-${{ needs.version_reader.outputs.version }}.zip
          asset_content_type: application/zip
      - name: Upload License
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ~/v8/v8/LICENSE.v8
          asset_name: LICENSE
          asset_content_type: text/plain

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [version_reader]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.version_reader.outputs.version }}
          release_name: v${{ needs.version_reader.outputs.version }}
          draft: true
          prerelease: false
